### PR TITLE
Fix ACS CTE for subarrays

### LINKED ISSUE #161: HSTIO error followed by double free of corruption
https://ssb.stsci.edu/pandokia/pandokia.cgi?query=detail&qid=2880

The above pandokia regeression test exposed a bug (or two).

```
PCTECORR COMPLETE
Outputting chip 1

*** ERROR in HST I/O functions:
Filename jb5s01fnq_blc_tmp.fits EXTNAME ERR EXTVER 1 CFITSIO status 207
Keyword name contains embedded space(s):  RHERIT 
Error writing image array.

*** ERROR in HST I/O functions:
Filename jb5s01fnq_blc_tmp.fits EXTNAME ERR EXTVER 1 CFITSIO status 207
Keyword name contains embedded space(s):  RHERIT 
Error writing image array.
*** glibc detected *** calacs.e: double free or corruption (!prev): 0x00000000021bf430 ***
```

From this info it is not clear whether the bug is in the CTE code or something after it, or is in the CTE code but at the end when the file is written to thus creating the corrupt *_blc.fits file.

Below is the full log.
```
 Pandokia

Test detail

test_run	conda-conda_tests_2017-06-28-10:30:01
key_id	103417582
project	hstcal
host	nott
context	dev:2.7.13
test_name	acs/calacs_e/wfc_sub5_noniraf-gen2cte.test_wfc_sub5_noniraf_gen2cte
contact	 
status	E
attn	Y
test_runner	nose
start_time	2017-06-28 13:03:33.247000
end_time	2017-06-28 13:08:27.234000
location	/srv/rt/hstcal/acs/calacs_e/wfc_sub5_noniraf-gen2cte.py
tda_cmp_0_file	jb5s01fnq_flt.fits
tda_cmp_0_ignorekeys	['filename', 'date', 'iraf-tlm', 'fitsdate', 'opus_ver', 'cal_ver', 'proctime']
tda_cmp_1_file	jb5s01fnq_flc.fits
tda_cmp_1_ignorekeys	['filename', 'date', 'iraf-tlm', 'fitsdate', 'opus_ver', 'cal_ver', 'proctime']
tda_description	Process a single 2K WFC subarray dataset with PCTECORR.
tda_title	CALACS: WFC 2K Subarray with PCTECORR
tda__okfile	/srv/rt/hstcal/acs/calacs_e/okfile/wfc_sub5_noniraf-gen2cte.test_wfc_sub5_noniraf_gen2cte.okfile
tra_exception	Exception('fitsdiff error - exited 2',)
back to treewalk
status history
Log:
/srv/iraf/bldtmp/pifW/p/envs/dev/bin/calacs.e
WARNING: using pcteTab file 'new_acs_pctetab_updated.fits'
(pctecorr) Using generation 2 CTE algorithm
(pctecorr) Using cmd line specified PCTETAB file: 'new_acs_pctetab_updated.fits'
Setting max threads to 4 out of 4 available


CALACSBEG*** CALACS -- Version 9.2.0 (01-Jun-2017) ***
Begin    28-Jun-2017 13:03:33 EDT


Input    jb5s01fnq_raw.fits
Processing SINGLE image jb5s01fnq_raw.fits...
LoadAsn:  Processing SINGLE exposure
Trying to open jb5s01fnq_raw.fits...
Read in Primary header from jb5s01fnq_raw.fits...

NUMBER of MEMBERS in TABLE: 1  PRODUCTS: 1  SUB-PRODUCTS: 1
Exposure-- Processing SINGLE Exposure jb5s01fnq_raw.fits 

CALACS: Detector ACS, type 1 
CALACS: processing a CCD product
CALACS: processing CCD product 0
CALACS: processing posid = 1
Warning    RPTCORR will be omitted because there's only one image.
CALACS: Got reference file information
CALACS: Processing switches set... 


CALACSBEG*** ACSCCD -- Version 9.2.0 (01-Jun-2017) ***
Begin    28-Jun-2017 13:03:33 EDT
Input    jb5s01fnq_raw.fits
Output   jb5s01fnq_blv_tmp.fits
Trying to open jb5s01fnq_raw.fits...
Read in Primary header from jb5s01fnq_raw.fits...
APERTURE WFC1-2K
FILTER1 CLEAR1L
FILTER2 F814W
DETECTOR WFC
DESCRIP read in as: 

DESCRIP read in as: 

DESCRIP read in as: 



CCDTAB   jref$uc82140bj_ccd.fits
CCDTAB   PEDIGREE=inflight
CCDTAB   DESCRIP =July 2009
Found trim values of: x(0,22) y(0,0)


DQICORR  PERFORM
DQITAB   jref$t3n1116nj_bpx.fits
DQICORR  COMPLETE


BIASCORR PERFORM
BIASFILE jref$w9c1408aj_bia.fits
BIASFILE PEDIGREE=INFLIGHT 18/02/2011 18/02/2011
BIASFILE DESCRIP =Exact copy of v382219bj_bia.fits with correct useafter date.-------
Ratio of (1,1) with offset =(0,0)
BIAS image and input are the same size 
BIASCORR COMPLETE


BLEVCORR PERFORM
OSCNTAB  newwfc_osc.fits
(blevcorr) No virtual overscan region specified.
(blevcorr) Bias drift correction will not be applied.
(FitToOverscan) biassecta=(2048,2053) biassectb=(0,0) npix=6
(blevcorr) Rejected 3 bias values from fit.
Computed a fit with slope of -0.00072239 and intercept of 4021.46
Bias level from overscan has been subtracted;
     mean of bias levels subtracted was 4021.46 electrons.
     bias level of 4021.46 electrons was subtracted for AMP B.
BLEVCORR COMPLETE

    Uncertainty array initialized,
    readnoise =3.91,
    gain =1.886,
   default bias levels =4060.6,


SINKCORR OMIT
Writing out image with trimx = 0,22, trimy = 0,0
Outputting chip 1


End      28-Jun-2017 13:03:34 EDT


*** ACSCCD complete ***


CALACSBEG*** ACSCTE -- Version 9.2.0 (01-Jun-2017) ***
Begin    28-Jun-2017 13:03:34 EDT
Input    jb5s01fnq_blv_tmp.fits
Output   jb5s01fnq_blc_tmp.fits
Trying to open jb5s01fnq_blv_tmp.fits...
Read in Primary header from jb5s01fnq_blv_tmp.fits...
APERTURE WFC1-2K
FILTER1 CLEAR1L
FILTER2 F814W
DETECTOR WFC
DESCRIP read in as: 

DESCRIP read in as: 

Warning    (pctecorr) USING PCTETAB SPECIFIED BY '--pctetab new_acs_pctetab_updated.fits' AND NOT THAT FROM IMAGE HEADER!!!
DESCRIP read in as: 



CCDTAB   jref$uc82140bj_ccd.fits
CCDTAB   PEDIGREE=inflight
CCDTAB   DESCRIP =July 2009


PCTECORR PERFORM
PCTEFILE new_acs_pctetab_updated.fits
Trying to open new_acs_pctetab_updated.fits...
Read in Primary header from new_acs_pctetab_updated.fits...
(pctecorr) Generation 2 PCTETAB file auto-detected.
(pctecorr) Reading CTE parameters from PCTETAB file: 'new_acs_pctetab_updated.fits'...
Trying to open new_acs_pctetab_updated.fits...
Read in Primary header from new_acs_pctetab_updated.fits...

CTE_NAME: PixelCTE 2017
CTE_VER: 2.0
CTEDATE0: 52334.9
CTEDATE1: 57710.4
PCTETLEN: 60
PCTERNOI: 3.250000
PCTERNFOR: 5
PCTERNPAR: 7
PCTENSMD: 0
PCTETRSH: -10
FIXROCR: 1
Reading in image from extension 3
Reading in image from extension 4
ERROR:    Keyword = `PCTENSMD'.
ERROR:    Keyword = `PCTETLEN'.
ERROR:    Keyword = `PCTERNOI'.
ERROR:    Keyword = `PCTENFOR'.
ERROR:    Keyword = `PCTENPAR'.
ERROR:    Keyword = `FIXROCR'.
(pctecorr) Read noise level PCTERNCL: 3.250000
(pctecorr) Readout simulation forward modeling iterations PCTENFOR: 5
(pctecorr) Number of iterations used in the parallel transfer PCTENPAR: 7
(pctecorr) CTE_FRAC: 0.606767
(pctecorr) PCTETAB read
(pctecorr) Using parallel processing provided by OpenMP inside CTE routine
(pctecorr) Performing CTE correction for amp B
(pctecorr) Calculating smooth readnoise image...
(pctecorr) Time taken to smooth image: 2.97(s) with 4 threads
(pctecorr) ...complete.
(pctecorr) Creating charge trap image...
(pctecorr) Time taken to populate pixel trap map image: 0.01(s) with 4 threads
(pctecorr) ...complete.
(pctecorr) Running correction algorithm...
(pctecorr) ...complete.
(pctecorr) Total count difference (corrected-raw) incurred from correction: 192895.484375 (0.000000%)
(pctecorr) CTE run time for current chip: 277.18(s) with 4 procs/threads

PCTECORR COMPLETE
Outputting chip 1

*** ERROR in HST I/O functions:
Filename jb5s01fnq_blc_tmp.fits EXTNAME ERR EXTVER 1 CFITSIO status 207
Keyword name contains embedded space(s):  RHERIT 
Error writing image array.

*** ERROR in HST I/O functions:
Filename jb5s01fnq_blc_tmp.fits EXTNAME ERR EXTVER 1 CFITSIO status 207
Keyword name contains embedded space(s):  RHERIT 
Error writing image array.
*** glibc detected *** calacs.e: double free or corruption (!prev): 0x00000000021bf430 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3810275f3e]
/lib64/libc.so.6[0x3810278dd0]
calacs.e[0x43ff8a]
calacs.e[0x440001]
calacs.e[0x440191]
calacs.e[0x42df92]
calacs.e[0x4148e4]
calacs.e[0x406f2b]
calacs.e[0x408563]
calacs.e[0x4053c8]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x381021ed1d]
calacs.e[0x404ec9]
======= Memory map: ========
00400000-00573000 r-xp 00000000 fd:02 57284595                           /srv/iraf/bldtmp/pifW/p/envs/dev/bin/calacs.e
00773000-00776000 rw-p 00173000 fd:02 57284595                           /srv/iraf/bldtmp/pifW/p/envs/dev/bin/calacs.e
00776000-007df000 rw-p 00000000 00:00 0 
01199000-041ff000 rw-p 00000000 00:00 0                                  [heap]
380fe00000-380fe20000 r-xp 00000000 fd:00 128991                         /lib64/ld-2.12.so
381001f000-3810021000 r--p 0001f000 fd:00 128991                         /lib64/ld-2.12.so
3810021000-3810022000 rw-p 00021000 fd:00 128991                         /lib64/ld-2.12.so
3810022000-3810023000 rw-p 00000000 00:00 0 
3810200000-381038a000 r-xp 00000000 fd:00 128997                         /lib64/libc-2.12.so
381038a000-381058a000 ---p 0018a000 fd:00 128997                         /lib64/libc-2.12.so
381058a000-381058e000 r--p 0018a000 fd:00 128997                         /lib64/libc-2.12.so
381058e000-3810590000 rw-p 0018e000 fd:00 128997                         /lib64/libc-2.12.so
3810590000-3810594000 rw-p 00000000 00:00 0 
3810600000-3810617000 r-xp 00000000 fd:00 129020                         /lib64/libpthread-2.12.so
3810617000-3810817000 ---p 00017000 fd:00 129020                         /lib64/libpthread-2.12.so
3810817000-3810818000 r--p 00017000 fd:00 129020                         /lib64/libpthread-2.12.so
3810818000-3810819000 rw-p 00018000 fd:00 129020                         /lib64/libpthread-2.12.so
3810819000-381081d000 rw-p 00000000 00:00 0 
3810a00000-3810a02000 r-xp 00000000 fd:00 129052                         /lib64/libdl-2.12.so
3810a02000-3810c02000 ---p 00002000 fd:00 129052                         /lib64/libdl-2.12.so
3810c02000-3810c03000 r--p 00002000 fd:00 129052                         /lib64/libdl-2.12.so
3810c03000-3810c04000 rw-p 00003000 fd:00 129052                         /lib64/libdl-2.12.so
3810e00000-3810e83000 r-xp 00000000 fd:00 129045                         /lib64/libm-2.12.so
3810e83000-3811082000 ---p 00083000 fd:00 129045                         /lib64/libm-2.12.so
3811082000-3811083000 r--p 00082000 fd:00 129045                         /lib64/libm-2.12.so
3811083000-3811084000 rw-p 00083000 fd:00 129045                         /lib64/libm-2.12.so
3811200000-3811207000 r-xp 00000000 fd:00 129023                         /lib64/librt-2.12.so
3811207000-3811406000 ---p 00007000 fd:00 129023                         /lib64/librt-2.12.so
3811406000-3811407000 r--p 00006000 fd:00 129023                         /lib64/librt-2.12.so
3811407000-3811408000 rw-p 00007000 fd:00 129023                         /lib64/librt-2.12.so
7fa74c000000-7fa74c021000 rw-p 00000000 00:00 0 
7fa74c021000-7fa750000000 ---p 00000000 00:00 0 
7fa754000000-7fa754023000 rw-p 00000000 00:00 0 
7fa754023000-7fa758000000 ---p 00000000 00:00 0 
7fa75c000000-7fa75c023000 rw-p 00000000 00:00 0 
7fa75c023000-7fa760000000 ---p 00000000 00:00 0 
7fa764000000-7fa764023000 rw-p 00000000 00:00 0 
7fa764023000-7fa768000000 ---p 00000000 00:00 0 
7fa76b8f4000-7fa76b90a000 r-xp 00000000 fd:02 57280767                   /srv/iraf/bldtmp/pifW/p/envs/dev/lib/libgcc_s.so.1
7fa76b90a000-7fa76bb09000 ---p 00016000 fd:02 57280767                   /srv/iraf/bldtmp/pifW/p/envs/dev/lib/libgcc_s.so.1
7fa76bb09000-7fa76bb0a000 rw-p 00015000 fd:02 57280767                   /srv/iraf/bldtmp/pifW/p/envs/dev/lib/libgcc_s.so.1
7fa76bb0a000-7fa76bb0b000 rw-p 00074000 fd:02 57280767                   /srv/iraf/bldtmp/pifW/p/envs/dev/lib/libgcc_s.so.1
7fa76bb0b000-7fa76bb0c000 ---p 00000000 00:00 0 
7fa76bb0c000-7fa76c50c000 rw-p 00000000 00:00 0 
7fa76c50c000-7fa76c50d000 ---p 00000000 00:00 0 
7fa76c50d000-7fa76cf0d000 rw-p 00000000 00:00 0 
7fa76cf0d000-7fa76cf0e000 ---p 00000000 00:00 0 
7fa76cf0e000-7fa76d912000 rw-p 00000000 00:00 0 
7fa76d912000-7fa76d932000 r-xp 00000000 fd:02 57280774                   /srv/iraf/bldtmp/pifW/p/envs/dev/lib/libgomp.so.1.0.0
7fa76d932000-7fa76db32000 ---p 00020000 fd:02 57280774                   /srv/iraf/bldtmp/pifW/p/envs/dev/lib/libgomp.so.1.0.0
7fa76db32000-7fa76db35000 rw-p 00020000 fd:02 57280774                   /srv/iraf/bldtmp/pifW/p/envs/dev/lib/libgomp.so.1.0.0
7fa76db35000-7fa76db36000 rw-p 00000000 00:00 0 
7fa76db52000-7fa76db56000 rw-p 00000000 00:00 0 
7ffdd8ba7000-7ffdd8bbc000 rw-p 00000000 00:00 0                          [stack]
7ffdd8bc0000-7ffdd8bc1000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

COMPARE: jb5s01fnq_flt.fits
['fitsdiff', '-k', 'filename,date,iraf-tlm,fitsdate,opus_ver,cal_ver,proctime', 'jb5s01fnq_flt.fits', 'ref/jb5s01fnq_flt_ref_gen2cte.fits']
ERROR: 'jb5s01fnq_flt.fits' is not an existing file, directory, or wildcard pattern; see `fitsdiff --help` for more usage help.
ERROR fitsdiff error - exited 2

COMPARE: jb5s01fnq_flc.fits
['fitsdiff', '-k', 'filename,date,iraf-tlm,fitsdate,opus_ver,cal_ver,proctime', 'jb5s01fnq_flc.fits', 'ref/jb5s01fnq_flc_ref_gen2cte.fits']
ERROR: 'jb5s01fnq_flc.fits' is not an existing file, directory, or wildcard pattern; see `fitsdiff --help` for more usage help.
ERROR fitsdiff error - exited 2

  File "/srv/iraf/bldtmp/pifW/p/envs/dev/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/srv/iraf/bldtmp/pifW/p/envs/dev/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/srv/rt/hstcal/acs/calacs_e/wfc_sub5_noniraf-gen2cte.py", line 93, in test_wfc_sub5_noniraf_gen2cte
    filecomp.compare_files( output, ( __file__, testname ), tda = tda,)
  File "/srv/iraf/bldtmp/pifW/p/envs/dev/lib/python2.7/site-packages/pandokia/helpers/filecomp.py", line 701, in compare_files
    raise ret_exc
Exception('fitsdiff error - exited 2',)
```

### PR DESCRIPTION
**Pull request by jamienoss**
fixes #161

Signed-off-by: James Noss <jnoss@stsci.edu>

### CODE REVIEW

File: pkg/acs/calacs/include/acs.h [hunk 1]
```diff
@@ -13,6 +13,9 @@
 # define ACS_FITS_REC       82
 # define SZ_STRKWVAL        68
 
+#define ACS_WFC_N_COLUMNS_PER_CHIP_INCL_OVERSCAN 4144
```
Comment (pllim) [inline pkg/acs/calacs/include/acs.h]: Does this work for subarrays? If yes, then I have no objection.

Comment (jamienoss) [inline pkg/acs/calacs/include/acs.h]: Yes, this is only for aligning the image against the scalebycol data in the ``PCTETAB``, _c.f._ [here for more detail](https://github.com/jamienoss/hstcal/blob/4e2c39d8ff67007ffd86977ba9e6947d1a017cb3/pkg/acs/calacs/acscte/dopcte-gen2.c#L108-L111)
```c
// razColumnOffset is used to align the image with the column scaling (SCLBYCOL) in the PCTETAB.
        // The SCLBYCOL array is 8192 cols wide which is 2048*4 and therefore does NOT include the physical
        // overscan columns (24 for ACS WFC) like this array does for calwf3.
        // The raz format is all 4 amps side by side in CDAB order.
```
Does it look like it should work for subarrays to you?

Comment (jamienoss) [inline pkg/acs/calacs/include/acs.h]: Are you really specifically referring to ``ACS_WFC_N_COLUMNS_PER_CHIP_INCL_OVERSCAN``? As this isn't actually used, it's really only for added understanding of what ``ACS_WFC_N_COLUMNS_PER_CHIP_EXCL_OVERSCAN`` is referring to.

Comment (pllim) [inline pkg/acs/calacs/include/acs.h]: Theoretically, yes. ACS does not have crazy cross-chip subarrays that I heard WFC3 has. Let's merge this and see if tests for subarrays pass tomorrow, just to be sure.

Comment (jamienoss) [inline pkg/acs/calacs/include/acs.h]: So ``ctePars->columnOffset`` is obatined from [here](https://github.com/jamienoss/hstcal/blob/4e2c39d8ff67007ffd86977ba9e6947d1a017cb3/pkg/acs/calacs/acscte/dopcte-gen2.c#L106-L107)
```c
...
 if (get_amp_array_size_acs_cte(acs, chipImage, ampID, amploc, ccdamp,
                               &amp_xsize, &amp_ysize, &amp_xbeg,
                               &amp_xend, &amp_ybeg, &amp_yend))
        {
            freeOnExit(&ptrReg);
            return (status);
        }
...
ctePars->columnOffset = amp_xbeg;
ctePars->rowOffset = amp_ybeg;
...
```

where ``amp_xbeg`` gives the offset of the image in reference to the beginning of the chip excluding overscan regions (right?). So even if it the subarray went over the chip boundary this would be equivalent to just two individual subarrays on different chips.

Comment (jamienoss) [inline pkg/acs/calacs/include/acs.h]: This should now be able to correct subarrays of any size irrespective of which chip they are on.
BTW there is only one subarray test in our regression suite and I already rigorously tested this (this time) across two macs and nott. It works fine. I also tested this on the fullframe images in the suite. I say this because once this is merged into ``candidate-1.3.0`` it'll be tagged and delivered to DMS.

Comment (jamienoss) [inline pkg/acs/calacs/include/acs.h]: @pllim do these comments and explanations sound ok to you?

Comment (pllim) [inline pkg/acs/calacs/include/acs.h]: It sure does. Thanks! 👍

Comment (jamienoss) [inline pkg/acs/calacs/include/acs.h]: Awesome, thanks.
